swagger: "2.0"
info:
  description: "This is a sample server"
  version: "1.0.0"
  title: "Swagger Example 2.0"
tags:
  - name: patients
    description: patients API
  - name: orders
    description: orders API
  - name: relevances
    description: relevances API
schemes:
  - "https"
  - "http"
paths:
  # [GET] patients
  /patients:
    get:
      tags:
        - patients
      summary: Find Many Patients
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PatientWithOrders"
        500:
          description: "Server Error"

    # [POST] patients
    post:
      tags:
        - patients
      summary: Add Patient
      parameters:
        - name: body
          in: body
          description: Patient Body
          required: true
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] patients/id
  /patients/{id}:
    get:
      tags:
        - patients
      summary: Find Patient By Id
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          type: string
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] patients/id
    put:
      tags:
        - patients
      summary: Update Patient By Id
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          type: string
        - name: body
          in: body
          description: Patient Body
          required: true
          schema:
            $ref: "#/definitions/PatientBody"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] patients/id
    delete:
      tags:
        - patients
      summary: Delete Patient By Id
      parameters:
        - name: id
          in: path
          description: Patient Id
          required: true
          type: string
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] orders
  /orders:
    get:
      tags:
        - orders
      summary: Find Many Orders
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Order"
        500:
          description: "Server Error"

    # [POST] orders
    post:
      tags:
        - orders
      summary: Add Order
      parameters:
        - name: body
          in: body
          description: Order Body
          required: true
          schema:
            $ref: "#/definitions/OrderBody"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [POST] orders/withPatient
  /orders/withPatient:
    post:
      tags:
        - orders
      summary: Add Order With Patient
      parameters:
        - name: body
          in: body
          description: Order Body
          required: true
          schema:
            $ref: "#/definitions/PatientOrderBody"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/Order"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [GET] orders/id
  /orders/{id}:
    get:
      tags:
        - orders
      summary: Find Order By Id
      parameters:
        - name: id
          in: path
          description: Order Id
          required: true
          type: string
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Order"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [PUT] orders/id
    put:
      tags:
        - orders
      summary: Update Order By Id
      parameters:
        - name: id
          in: path
          description: Order Id
          required: true
          type: string
        - name: body
          in: body
          description: Order Body
          required: true
          schema:
            $ref: "#/definitions/OrderBody"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Order"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

    # [DELETE] orders/id
    delete:
      tags:
        - orders
      summary: Delete Order By Id
      parameters:
        - name: id
          in: path
          description: Order Id
          required: true
          type: string
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Order"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [PUT] relevances/assign
  /relevances/assign:
    put:
      tags:
        - relevances
      summary: Assign Relevances
      parameters:
        - name: body
          in: body
          description: Assign Relevance Body
          required: true
          schema:
            $ref: "#/definitions/AssignRelevanceBody"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/AssignRelevance"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [PUT] relevances/unassign
  /relevances/unassign:
    put:
      tags:
        - relevances
      summary: Unassign Relevances
      parameters:
        - name: body
          in: body
          description: Unassign Relevance Body
          required: true
          schema:
            $ref: "#/definitions/UnassignRelevanceBody"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/UnassignRelevance"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

  # [PUT] relevances/reassign
  /relevances/reassign:
    put:
      tags:
        - relevances
      summary: Reassign Relevances
      parameters:
        - name: body
          in: body
          description: Reassign Relevance Body
          required: true
          schema:
            $ref: "#/definitions/ReassignRelevanceBody"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ReassignRelevance"
        400:
          description: "Bad Request"
        409:
          description: "Conflict"
        500:
          description: "Server Error"

# definitions
definitions:
  Patient:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
        format: "varchar(45)"
      created_user:
        type: "string"
        format: "varchar(45)"
      created_date:
        type: "string"
        format: "date-time"
      updated_user:
        type: "string"
        format: "varchar(45)"
      updated_date:
        type: "string"
        format: "date-time"
    xml:
      name: "Patient"
  PatientWithOrders:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
        format: "varchar(45)"
      created_user:
        type: "string"
        format: "varchar(45)"
      created_date:
        type: "string"
        format: "date-time"
      updated_user:
        type: "string"
        format: "varchar(45)"
      updated_date:
        type: "string"
        format: "date-time"
      orders:
        type: "array"
        items:
          $ref: "#/definitions/Order"
    xml:
      name: "PatientWithOrders"
  Order:
    type: "object"
    properties:
      id:
        type: "string"
      message:
        type: "string"
        format: "varchar(255)"
      created_user:
        type: "string"
        format: "varchar(45)"
      created_date:
        type: "string"
        format: "date-time"
      updated_user:
        type: "string"
        format: "varchar(45)"
      updated_date:
        type: "string"
        format: "date-time"
    xml:
      name: "Patient"
  Relevance:
    type: "object"
    properties:
      id:
        type: "string"
      type:
        type: "string"
        format: "varchar(45)"
      first_id:
        type: "string"
        format: "varchar(255)"
      second_id:
        type: "string"
        format: "varchar(255)"
      third_id:
        type: "string"
        format: "varchar(255)"
      created_user:
        type: "string"
        format: "varchar(45)"
      created_date:
        type: "string"
        format: "date-time"
      updated_user:
        type: "string"
        format: "varchar(45)"
      updated_date:
        type: "string"
        format: "date-time"
    xml:
      name: "Relevance"
  PatientBody:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Patient Name
  OrderBody:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        description: Order Message
  PatientOrderBody:
    type: object
    required:
      - patientId
      - message
    properties:
      message:
        type: string
        description: Order Message
      patientId:
        type: string
        description: Specify which patient have the order
  AssignRelevanceBody:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        description: Relevance Type
      first_ids:
        type: array
        items:
          type: "string"
        description: First Ids of Relevance
      second_ids:
        type: array
        items:
          type: "string"
        description: Second Ids of Relevance
      third_ids:
        type: array
        items:
          type: "string"
        description: Third Ids of Relevance
  UnassignRelevanceBody:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        description: Relevance Type
      first_ids:
        type: array
        items:
          type: "string"
        description: First Ids of Relevance
      second_ids:
        type: array
        items:
          type: "string"
        description: Second Ids of Relevance
      third_ids:
        type: array
        items:
          type: "string"
        description: Third Ids of Relevance
  ReassignRelevanceBody:
    type: object
    required:
      - assign
      - reassign
    properties:
      assign:
        type: object
        required:
          - type
        properties:
          type:
            type: string
            description: Relevance Type
          first_ids:
            type: array
            items:
              type: "string"
            description: First Ids of Relevance
          second_ids:
            type: array
            items:
              type: "string"
            description: Second Ids of Relevance
          third_ids:
            type: array
            items:
              type: "string"
            description: Third Ids of Relevance
        description: Assign Body
      reassign:
        type: object
        required:
          - type
        properties:
          type:
            type: string
            description: Relevance Type
          first_ids:
            type: array
            items:
              type: "string"
            description: First Ids of Relevance
          second_ids:
            type: array
            items:
              type: "string"
            description: Second Ids of Relevance
          third_ids:
            type: array
            items:
              type: "string"
            description: Third Ids of Relevance
        description: Reassign Body
